<?php

namespace Database\Factories;

use App\Enums\AssetAssignmentStatus;
use App\Enums\AssetCategory;
use App\Enums\AssetCondition;
use App\Enums\EntityType;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Asset>
 */
class AssetFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $kategori = fake()->randomElement(AssetCategory::cases());
        $entity = fake()->randomElement(EntityType::cases());
        $tahun = fake()->numberBetween(2020, 2026);

        return [
            'entity' => $entity,
            'kategori' => $kategori,
            // nomor_inventaris will be auto-generated by observer
            'nama_barang' => $this->generateRealisticName($kategori),
            'deskripsi' => fake()->optional(0.6)->sentence(),
            'jumlah' => fake()->numberBetween(1, 10),
            'satuan' => $this->getSatuan($kategori),
            'kondisi' => fake()->randomElement([
                AssetCondition::Baik->value => 0.8,  // 80% good condition
                AssetCondition::Rusak->value => 0.2, // 20% damaged
            ]),
            'status_assignment' => AssetAssignmentStatus::Available,
            'tahun_pembelian' => $tahun,
            'nilai_pembelian' => fake()->numberBetween(1000000, 50000000), // 1M - 50M IDR
            'lokasi' => fake()->optional(0.7)->randomElement([
                'Kantor Pusat Jakarta',
                'Kantor Cabang Surabaya',
                'Training Center Bandung',
                'Ruang Administrasi',
                'Ruang IT',
                'Ruang Direksi',
                'Gudang A',
                'Gudang B',
            ]),
            'keterangan' => fake()->optional(0.3)->sentence(),
            'created_by' => User::factory(),
            'updated_by' => null,
        ];
    }

    /**
     * Generate realistic Indonesian equipment names based on category.
     */
    protected function generateRealisticName(AssetCategory $kategori): string
    {
        return match ($kategori) {
            AssetCategory::Elektronik => fake()->randomElement([
                'Laptop Lenovo ThinkPad',
                'Komputer Desktop HP',
                'Printer Canon Pixma',
                'Monitor LG 24 inch',
                'Scanner Epson',
                'Proyektor Infocus',
                'UPS APC 1000VA',
                'Kamera CCTV Hikvision',
                'Access Point TP-Link',
                'Hard Disk External 2TB',
            ]),
            AssetCategory::Furniture => fake()->randomElement([
                'Meja Kerja Kayu Jati',
                'Kursi Kantor Ergonomis',
                'Lemari Arsip Besi',
                'Meja Rapat 6 Orang',
                'Kursi Tamu Sofa',
                'Rak Buku 5 Tingkat',
                'Filling Cabinet 4 Laci',
                'White Board 2x1 meter',
                'Partisi Ruangan Aluminium',
            ]),
            AssetCategory::DokumenIjin => fake()->randomElement([
                'Ijin Operasional LPK',
                'SIUP Perusahaan',
                'TDP (Tanda Daftar Perusahaan)',
                'Ijin Pengerahan Tenaga Kerja',
                'Akreditasi LPK BAN-LPK',
                'Sertifikat ISO 9001:2015',
            ]),
            AssetCategory::PerlengkapanKantor => fake()->randomElement([
                'AC Split 1 PK',
                'Dispenser Air Panas Dingin',
                'Telepon Kantor Panasonic',
                'Mesin Fotokopi Canon',
                'Mesin Absensi Fingerprint',
                'Safe Box Brankas',
                'Kalkulator Casio',
                'Stapler Joyko Heavy Duty',
            ]),
            AssetCategory::Kendaraan => fake()->randomElement([
                'Mobil Toyota Avanza 2023',
                'Motor Honda Beat',
                'Mobil Daihatsu Xenia',
                'Motor Yamaha NMAX',
                'Mobil Suzuki Ertiga',
            ]),
            AssetCategory::Lainnya => fake()->randomElement([
                'Genset 5000 Watt',
                'Tangga Lipat Aluminium',
                'Fire Extinguisher APAR',
                'Tenda Pesta 4x6 meter',
                'Sound System Portable',
            ]),
        };
    }

    /**
     * Get appropriate unit (satuan) based on category.
     */
    protected function getSatuan(AssetCategory $kategori): string
    {
        return match ($kategori) {
            AssetCategory::Elektronik => 'Unit',
            AssetCategory::Furniture => 'Unit',
            AssetCategory::DokumenIjin => 'Dokumen',
            AssetCategory::PerlengkapanKantor => 'Unit',
            AssetCategory::Kendaraan => 'Unit',
            AssetCategory::Lainnya => fake()->randomElement(['Unit', 'Set', 'Buah']),
        };
    }

    /**
     * Indicate the asset belongs to LPK entity.
     */
    public function forLPK(): static
    {
        return $this->state(fn (array $attributes) => [
            'entity' => EntityType::LPK,
        ]);
    }

    /**
     * Indicate the asset belongs to PT entity.
     */
    public function forPT(): static
    {
        return $this->state(fn (array $attributes) => [
            'entity' => EntityType::PT,
        ]);
    }

    /**
     * Indicate the asset is in good condition.
     */
    public function inGoodCondition(): static
    {
        return $this->state(fn (array $attributes) => [
            'kondisi' => AssetCondition::Baik,
        ]);
    }

    /**
     * Indicate the asset is damaged.
     */
    public function damaged(): static
    {
        return $this->state(fn (array $attributes) => [
            'kondisi' => AssetCondition::Rusak,
        ]);
    }

    /**
     * Indicate the asset is currently assigned.
     */
    public function assigned(): static
    {
        return $this->state(fn (array $attributes) => [
            'status_assignment' => AssetAssignmentStatus::Assigned,
        ]);
    }
}
